version: "3.4"

services:
  backend:
    image: ccs/reruitment-portal-node
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "4376:4376"
    volumes:
      - ./images:/container/path/images
    restart: always